@startuml

Patient "1..." *-> "0...*" Picture : has
Patient "1..." *-> "1...*" Diseases : suffers

class Patient{
-FullName:String
-ID:int
-BirthDate:Date
-Sex:boolean
-Weight:Double
-Height:Double
-Address:String
-Picture:List
-Diseases:List


+Patient()
+Patient(FullName:String,ID:int,BirthDate:Date,Sex:boolean,Weight:Double,Height:Double,Address:String,Picture:List,Diseases:List)
+getFullName():String
+getID():int
+getBirthDate():Date
+getSex():boolean
+getWeight():Double
+getHeight():Double
+getAddress():String
+addPicture(picture:Picture):void
+deletePicture(picture:Picture):void
+addDiseases(diseases:Diseases):void
+deleteDiseases((diseases:Diseases):void







}
class Diseases{
-Name:String
-Date:Date
-Remedy:String
+Diseases()
+Diseases(Name:String,Date:Date,Remedy:String)
+getName():String
+setName(Name:String):void
+getDate():Date
+setDate(Date:Date):void
+getRemedy():String
+setRemedy(Remedy:String):void
}
class Picture{
-Date:Date
-Type:String
-Advisement:String
+Picture()
+Picture(Date:Date,Type:String,Advisement:String)
+getDate():Date
+setDate((Date:Date):void
+getType():String
+setType(Type:String):void
+getAdvisement():String
+setAdvisement(Advisement:String):void

}





@enduml